# Generated by Django 4.0.5 on 2022-06-09 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('gradenumber', models.IntegerField(db_column='GradeNumber')),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTheme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('chapterid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('timelimit', models.DurationField()),
                ('chapterid', models.ForeignKey(db_column='ChapterId', on_delete=django.db.models.deletion.DO_NOTHING, to='prof.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='prof.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicRule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('questionscount', models.IntegerField()),
                ('questionthemeid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prof.questiontheme')),
                ('questiontypeid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prof.questiontype')),
                ('topicid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='prof.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('questionthemeid', models.ForeignKey(db_column='QuestionThemeId', on_delete=django.db.models.deletion.DO_NOTHING, to='prof.questiontheme')),
                ('questiontypeid', models.ForeignKey(db_column='QuestionTypeId', on_delete=django.db.models.deletion.DO_NOTHING, to='prof.questiontype')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='subjectid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.subject'),
        ),
        migrations.CreateModel(
            name='GradeQuestion',
            fields=[
                ('gradesid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='prof.grade')),
                ('questionsid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prof.question')),
            ],
        ),
    ]
