# Generated by Django 4.0.5 on 2022-06-09 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCatalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prof.imagecatalog'),
        ),
        migrations.AddField(
            model_name='question',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='prof.imagecatalog'),
        ),
    ]
