# Generated by Django 4.0.5 on 2022-06-09 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0003_profile_delete_usersubject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='level',
            new_name='advanced',
        ),
    ]
