# Generated by Django 4.0.5 on 2022-06-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_rename_level_image_advanced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='catalog',
        ),
        migrations.AddField(
            model_name='image',
            name='catalog',
            field=models.ManyToManyField(to='prof.imagecatalog'),
        ),
    ]
