# Generated by Django 4.0.5 on 2022-06-10 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0005_remove_image_catalog_image_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradequestion',
            name='questionsid',
        ),
        migrations.AddField(
            model_name='gradequestion',
            name='questiontypeid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prof.questiontype'),
        ),
    ]
